# Generated by Django 5.2.4 on 2025-09-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('steam_appid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('developers', models.CharField(max_length=255)),
                ('publishers', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('required_age', models.CharField(max_length=255)),
                ('n_achievements', models.CharField(max_length=255)),
                ('platforms', models.CharField(max_length=255)),
                ('is_released', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('additional_content', models.CharField(max_length=255)),
                ('total_reviews', models.CharField(max_length=255)),
                ('total_positive', models.CharField(max_length=255)),
                ('total_negative', models.CharField(max_length=255)),
                ('review_score', models.CharField(max_length=255)),
                ('review_score_desc', models.CharField(max_length=255)),
                ('positive_percentual', models.CharField(max_length=255)),
                ('metacritic', models.CharField(max_length=255)),
                ('is_free', models.CharField(max_length=255)),
                ('price_initial', models.CharField(max_length=255)),
            ],
        ),
    ]
